server:
  servlet:
    context-path: /course-api

spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    banner-mode: "console"
  sql:
    init:
      platform: postgres
